import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'



export default function ThankYou() {
  return (
    <div className={styles.container}>
      <Head>
        <title>D3G3N | Thank You</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Metaverse CoverJAM 
        </h1>

        <p className={styles.description}> 
          The song for the Jam: <strong>The Metaverse song </strong><br/>
          The Theme for the Jam: <strong>TBA </strong>           {/* <code className={styles.code}>pages/index.js</code> */}
        </p>

        <div className={styles.grid}>
     <form className="formStyles" action="https://formsubmit.co/your@email.com" method="POST">
        <center>
        <input type="text" name="name"  placeholder="Artist Name" required/>
        <input type="email" name="email" placeholder="Email Address" required/>
        <input type="text" name="name"  placeholder="Twitter Handle" required/>
        <input type="hidden" name="_next" value="/ThankYou"></input>
        <input type="text" name="Cover Art Title"  placeholder="Cover Art Title" required/>
        <input type="text" name="name"  placeholder="Cover Art Description" required/>
        <input type="text" name="name"  placeholder="Link To Cover Art" required/>
        <p><center>Submission Date is <strong>October 29th 12:00PM MST</strong></center>
        <br/>
        <center>Will be hosting tutorials on how to make a cover art so <strong>submit to early</strong></center>
        </p>
        
             <button type="submit">Send</button>
             </center>
    </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <h1>AmbienceStudios</h1>
          </span>
        </a>
      </footer>
    </div>
  )
}
